CREATE OR REPLACE STORAGE INTEGRATION luisAmigo_
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::920373024450:role/rolequipo4'
  STORAGE_ALLOWED_LOCATIONS = ('s3://equipo4/', 's3://equipo4/*')

DESC INTEGRATION luisAmigo_;

GRANT CREATE STAGE ON SCHEMA public TO ROLE ACCOUNTADMIN;

GRANT USAGE ON INTEGRATION luisAmigo_ TO ROLE ACCOUNTADMIN;

USE SCHEMA luisAmigo22.public;

CREATE OR REPLACE STAGE sensoLogguer
  STORAGE_INTEGRATION = luisAmigo_
  URL = 's3://equipo4/'
  FILE_FORMAT = (TYPE = 'JSON');

COPY INTO MY_TABLE
FROM @sensoLogguer
FILE_FORMAT = (TYPE = 'JSON')
 ON_ERROR = 'CONTINUE';


SELECT * FROM MY_TABLE;